services:
  - type: web
    name: bike-finder
    env: node
    plan: free
    buildCommand: npm install && cd client && npm install && cd .. && npm run build
    startCommand: npm start
    autoDeploy: true
